// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace AnyDoubts.Specs
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("List a user\'s answered questions")]
    public partial class ListAUserSAnsweredQuestionsFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ListUsersQuestions.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "List a user\'s answered questions", "In order to satisfy my curiosity about a given user\r\nAs a visitor of the site\r\nI " +
                    "want to see all the questions answered by that user", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Listing the questions for a user that has no answered questions")]
        public virtual void ListingTheQuestionsForAUserThatHasNoAnsweredQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listing the questions for a user that has no answered questions", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I am a visitor");
#line 8
 testRunner.And("There is a user called \"vintem\"");
#line 9
 testRunner.And("the user \"vintem\" has no answered questions");
#line 10
 testRunner.When("I visit \"vintem\"\'s profile page");
#line 11
 testRunner.Then("I should see \"The user has not answered any questions\"");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Listing the questions for a user that has answered questions")]
        public virtual void ListingTheQuestionsForAUserThatHasAnsweredQuestions()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listing the questions for a user that has answered questions", ((string[])(null)));
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I am a visitor");
#line 15
  testRunner.And("There is a user called \"vintem\"");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Question",
                        "Answer"});
            table1.AddRow(new string[] {
                        "Who are you?",
                        "I am vintem"});
            table1.AddRow(new string[] {
                        "What is your favorite movie?",
                        "The Last Dragon"});
#line 16
  testRunner.And("the user \"vintem\" has the following questions", ((string)(null)), table1);
#line 20
 testRunner.When("I visit \"vintem\"\'s profile page");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Question",
                        "Answer"});
            table2.AddRow(new string[] {
                        "Who are you?",
                        "I am vintem"});
            table2.AddRow(new string[] {
                        "What is your favorite movie?",
                        "The Last Dragon"});
#line 21
 testRunner.Then("I should see", ((string)(null)), table2);
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
